GET http://localhost:16300/hello
Accept: application/json

###

POST http://localhost:16300/hello/post
Accept: application/json
Content-Type: application/x-www-form-urlencoded

name=liuqiang

###
GET http://localhost:16300/test/list
Accept: application/json